# Trabalho 1: Analise de dados do IBGE sobre população, economia e desigualdade socioeconômica no Brasil

#### Disciplina: Mineração de Dados - 2026.2

Aluno: Leonardo Nascimento de Souza  
Matricula: 20240013771  
   
Aluno:  
Matricula:

#### 0. Visualizando as tabelas (provavelmente vai sumir ou mudar)

In [5]:
import numpy as np
import pandas as pd
from dataset import API
from IPython.display import display

api: API = API()
dataset: list[pd.DataFrame] = []

# Armazena as tabelas extraídas da API em uma lista
dataset.append(api.query("PIB por região - 2016/2022"))
dataset.append(api.query("Alfabetização por Região"))
# OUTRAS CONSULTAS...

In [6]:
for ds in dataset:
    display(ds)

  Codigo    Localidade   Ano PIB (Mil reais)
0      1         Norte  2016       337302084
1      1         Norte  2022       574672357
2      2      Nordeste  2016       898361847
3      2      Nordeste  2022      1388050457
4      3       Sudeste  2016      3333233480
5      3       Sudeste  2022      5373124618
6      4           Sul  2016      1067358361
7      4           Sul  2022      1674518608
8      5  Centro-Oeste  2016       633072229
9      5  Centro-Oeste  2022      1069310338

  Codigo    Localidade   Ano Taxa de Alfabetização
0      1         Norte  2016                  92.0
1      1         Norte  2022                  93.5
2      2      Nordeste  2016                  86.1
3      2      Nordeste  2022                  88.2
4      3       Sudeste  2016                  96.5
5      3       Sudeste  2022                  97.1
6      4           Sul  2016                  96.6
7      4           Sul  2022                  97.0
8      5  Centro-Oeste  2016                  94.8
9      5  Centro-Oeste  2022                  96.0

Visualizar tabela da API (debug)

In [7]:
import requests
import pandas as pd

url = "https://apisidra.ibge.gov.br/values/t/5938/n2/all/v/37/p/2016,2022"

response = requests.get(url)
response.raise_for_status()

data = response.json()

df = pd.DataFrame(data)

df

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Grande Região (Código),Grande Região,Variável (Código),Variável,Ano (Código),Ano
1,2,Grande Região,40,Mil Reais,337302084,1,Norte,37,Produto Interno Bruto a preços correntes,2016,2016
2,2,Grande Região,40,Mil Reais,574672357,1,Norte,37,Produto Interno Bruto a preços correntes,2022,2022
3,2,Grande Região,40,Mil Reais,898361847,2,Nordeste,37,Produto Interno Bruto a preços correntes,2016,2016
4,2,Grande Região,40,Mil Reais,1388050457,2,Nordeste,37,Produto Interno Bruto a preços correntes,2022,2022
5,2,Grande Região,40,Mil Reais,3333233480,3,Sudeste,37,Produto Interno Bruto a preços correntes,2016,2016
6,2,Grande Região,40,Mil Reais,5373124618,3,Sudeste,37,Produto Interno Bruto a preços correntes,2022,2022
7,2,Grande Região,40,Mil Reais,1067358361,4,Sul,37,Produto Interno Bruto a preços correntes,2016,2016
8,2,Grande Região,40,Mil Reais,1674518608,4,Sul,37,Produto Interno Bruto a preços correntes,2022,2022
9,2,Grande Região,40,Mil Reais,633072229,5,Centro-Oeste,37,Produto Interno Bruto a preços correntes,2016,2016
10,2,Grande Região,40,Mil Reais,1069310338,5,Centro-Oeste,37,Produto Interno Bruto a preços correntes,2022,2022

#### 2. Unificando os dados em um dataset

In [8]:
dados : pd.DataFrame = dataset[0]

for i in range(1, len(dataset)):
    dados = pd.merge(dados, dataset[i], how="inner", on=["Codigo", "Localidade", "Ano"])

dados

  Codigo    Localidade   Ano PIB (Mil reais) Taxa de Alfabetização
0      1         Norte  2016       337302084                  92.0
1      1         Norte  2022       574672357                  93.5
2      2      Nordeste  2016       898361847                  86.1
3      2      Nordeste  2022      1388050457                  88.2
4      3       Sudeste  2016      3333233480                  96.5
5      3       Sudeste  2022      5373124618                  97.1
6      4           Sul  2016      1067358361                  96.6
7      4           Sul  2022      1674518608                  97.0
8      5  Centro-Oeste  2016       633072229                  94.8
9      5  Centro-Oeste  2022      1069310338                  96.0